### ISSUE TITLE
Underline numbers

### ISSUE THREAD

**Issue by steelbrain** [steelbrain/number-range#8]
For visual ease

**Comment by steelbrain** [comment]
If we do this, we'll have to hard-code the font-size therefore it might not work for people with bigger font sizes.
Should we or should we not?

Ideas @natew @ncammarata

**Comment by ncammarata** [comment]
how about bolding the numbers?

**Comment by steelbrain** [comment]
Currently, we add an overlay with opacity of zero above the number with the same contents as the number, so it has the same height and width. If we want to change the contents of that overlay, we'll have to make it visible and by doing so we'll have to manually calculate the width of it. It's very simple to do so, but I'm not sure how to make it work with font-size changes
